"QUAL_72":
  "title" : "安吉县耕地质量等级面积及其占比"
  "group_field" : dj
  "group_field_values" : [1,2,3,4,5,6,7,8,9,10]
  "calc_field" : 'MJ'
  "start_position" : "B3"
  "seg_length" : 5
  "position_interval" : 3

"SUITI_62":
  "title" : "安吉县适宜类评价面积表"
  "group_field" : s_level
  "group_field_values" : [1,2,3,4,5,6]
  "calc_field" : 'MJ'
  "start_position" : "B3"
  "seg_length" : 0
  "position_interval" : 0

"QUAL_73":
  "title" : "安吉县各乡镇（街道）耕地评价综合指数及质量等级表"
  "limit_field" : "XZQMC"
  "calc_field" : 'MJ'
  "weight_field": "score"
  "street_start_position" : "A3"
  "score_start_position" : "B3"
  "level_start_position" : "C3"
  "level_table":
    - "level_name": "一等"
      "range": (x >= 0.9070)
    - "level_name": "二等"
      "range": (x >= 0.8806 and x < 0.9070)
    - "level_name": "三等"
      "range": (x >= 0.8543 and x < 0.8806)
    - "level_name": "四等"
      "range": (x >= 0.8279 and x < 0.8543)
    - "level_name": "五等"
      "range": (x >= 0.8015 and x < 0.8279)
    - "level_name": "六等"
      "range": (x >= 0.7751 and x < 0.8015)
    - "level_name": "七等"
      "range": (x >= 0.7488 and x < 0.7751)
    - "level_name": "八等"
      "range": (x >= 0.7224 and x < 0.7488)
    - "level_name": "九等"
      "range": (x >= 0.6960 and x < 0.7224)
    - "level_name": "十等"
      "range": (x < 0.6960)
# 74 类型开始
"QUAL_74":
  "title" : "安吉县各乡镇（街道）耕地质量等级面积分布表"
  "limit_field" : "XZQMC"
  "calc_field" : 'MJ'
  "group_field" : 'dj'
  "group_field_value" : [1,2,3,4,5,6,7,8,9,10]
  "street_start_position": "A4"
  "result_start_position": "C4"

"SUITI_56":
  "title" : "安吉县各乡镇（街道）土壤坡度等级面积分布表"
  "limit_field" : "XZQMC"
  "calc_field" : 'MJ'
  "group_field" : 'PD_new'
  "group_field_value" : [0,1,2,3,4,5]
  "street_start_position": "A4"
  "result_start_position": "C4"

"SUITI_57":
  "title" : "安吉县各乡镇（街道）土壤土层厚度等级面积分布表"
  "limit_field" : "XZQMC"
  "calc_field" : 'MJ'
  "group_field" : 'TCHD_new'
  "group_field_value" : [0,1,2,3,4,5]
  "street_start_position": "A4"
  "result_start_position": "C4"

"SUITI_58":
  "title" : "安吉县各乡镇（街道）土壤地表砾石丰度等级面积分布表"
  "limit_field" : "XZQMC"
  "calc_field" : 'MJ'
  "group_field" : 'DBLSFD_new'
  "group_field_value" : [0,1,2,3,4,5]
  "street_start_position": "A4"
  "result_start_position": "C4"

"SUITI_59":
  "title" : "安吉县各乡镇（街道）土壤质地等级等级面积分布表"
  "limit_field" : "XZQMC"
  "calc_field" : 'MJ'
  "group_field" : 'TRZD_new'
  "group_field_value" : [0,1,2,3,4,5]
  "street_start_position": "A4"
  "result_start_position": "C4"

"SUITI_60":
  "title" : "安吉县各乡镇（街道）土壤水资源条件等级面积分布表"
  "limit_field" : "XZQMC"
  "calc_field" : 'MJ'
  "group_field" : 'SZYTJ_new'
  "group_field_value" : [0,1,2,3,4,5]
  "street_start_position": "A4"
  "result_start_position": "C4"

"SUITI_61":
  "title" : "安吉县各乡镇（街道）土壤排水能力等级面积分布表"
  "limit_field" : "XZQMC"
  "calc_field" : 'MJ'
  "group_field" : 'PSNL_new'
  "group_field_value" : [0,1,2,3,4,5]
  "street_start_position": "A4"
  "result_start_position": "C4"

"SUITI_164":
  "title" : "安吉县各乡镇（街道）土壤侵蚀程度等级面积分布表"
  "limit_field" : "XZQMC"
  "calc_field" : 'MJ'
  "group_field" : 'QSCD_new'
  "group_field_value" : [0,1,2,3,4,5]
  "street_start_position": "A4"
  "result_start_position": "C4"

"SUITI_165":
  "title" : "安吉县各乡镇（街道）土壤盐碱化等级面积分布表"
  "limit_field" : "XZQMC"
  "calc_field" : 'MJ'
  "group_field" : 'TRYJH_new'
  "group_field_value" : [0,1,2,3,4,5]
  "street_start_position": "A4"
  "result_start_position": "C4"

"SUITI_166":
  "title" : "安吉县各乡镇（街道）土壤基岩出露丰度等级面积分布表"
  "limit_field" : "XZQMC"
  "calc_field" : 'MJ'
  "group_field" : 'JYCLFD_new'
  "group_field_value" : [0,1,2,3,4,5]
  "street_start_position": "A4"
  "result_start_position": "C4"

"SUITI_63":
  "title" : "安吉县土壤类型（亚类）适宜类评价分布表"
  "limit_field" : "XZQMC"
  "calc_field" : 'MJ'
  "group_field" : 's_level'
  "group_field_value" : [1,2,3,4,5,6]
  "street_start_position": "A4"
  "result_start_position": "C4"
# 74类型结束

"QUAL_75":
  "title" : "安吉县各乡镇（街道）耕地粮食生产潜能表"
  "limit_field" : "XZQMC"
  "calc_field" : 'MJ'
  "weight_field" : 'CN'
  "dl_field" : 'DLBM'
  "dl_rule": "'^01.*'"
  "street_start_position": "A4"
  "result_start_position": "B4"

# 64类型开始
"SUITI_64":
  "title" : "安吉县土壤类型（亚类）适宜类评价分布表"
  "limit_field" : "YL"
  "calc_field" : 'MJ'
  "group_field" : 's_level'
  "group_field_value" : [1,2,3,4,5,6]
  "col_start_position": "A4"
  "result_start_position": "C4"

"SUITI_65":
  "title" : "安吉县土壤农业利用适宜程度评价面积表"
  "limit_field" : "s_s_level"
  "calc_field" : 'MJ'
  "group_field" : 's_name'
  "group_field_value" : ['适宜耕地','适宜园地','适宜林地','适宜草地']
  "col_start_position": "A4"
  "result_start_position": "C4"
# 63类型结束

# 67类型开始
"SUITI_67":
  "title" : "安吉县耕地-适宜类面积错配表"
  "col_name_field" : "DLMC"
  "col_value_field" : "DLBM"
  "col_sum_rule" : "'^01'"
  "col_sum_name" : '耕地'
  "calc_field" : 'MJ'
  "group_field" : 's_name'
  "group_field_value" : ['适宜园地','适宜林地','适宜草地']
  "col_start_position": "A4"
  "result_start_position": "B4"

"SUITI_68":
  "title" : "安吉县园地-适宜类面积错配表"
  "col_name_field" : "DLMC"
  "col_value_field" : "DLBM"
  "col_sum_rule" : "'^02'"
  "col_sum_name" : '园地'
  "calc_field" : 'MJ'
  "group_field" : 's_name'
  "group_field_value" : ['适宜耕地','适宜林地','适宜草地']
  "col_start_position": "A4"
  "result_start_position": "B4"

"SUITI_69":
  "title" : "安吉县林地-适宜类面积错配表"
  "col_name_field" : "DLMC"
  "col_value_field" : "DLBM"
  "col_sum_rule" : "'^03'"
  "col_sum_name" : '林地'
  "calc_field" : 'MJ'
  "group_field" : 's_name'
  "group_field_value" : ['适宜耕地','适宜园地','适宜草地']
  "col_start_position": "A4"
  "result_start_position": "B4"

"SUITI_70":
  "title" : "安吉县草地-适宜类面积错配表"
  "col_name_field" : "DLMC"
  "col_value_field" : "DLBM"
  "col_sum_rule" : "'^04'"
  "col_sum_name" : '草地'
  "calc_field" : 'MJ'
  "group_field" : 's_name'
  "group_field_value" : ['适宜耕地','适宜园地','适宜林地']
  "col_start_position": "A4"
  "result_start_position": "B4"
# 67类型结束

"SUITI_71":
  "title" : "安吉县耕地后备资源面积表"
  "col_sum_names" : ["园地", "林地", "草地", "其他"]
  "col_sum_value" : ["'^02'", "'^03'", "'^04'", "'^(?!(01|02|03|04))'"]
  "col_name_field" : "DLMC"
  "col_value_field" : "DLBM"
  "calc_field" : "MJ"
  "group_field" : "s_level"
  "group_field_value" : [1, 2]
  "col_start_position" : "A4"
  "result_start_position" : "B4"

"SUITI_167":
  "title" : "安吉县各乡镇（街道）限制因素评级表"
  "col_name_field" : "XZQMC"
  "calc_field" : 'MJ'
  "group_value_list" : ['PD_new', 'TCHD_new', 'DBLSFD_new', 'TRZD_new', 'SZYTJ_new', 'PSNL_new', 'QSCD_new', 'JYCLFD_new']
  "group_start_position" : 'B3'
  "col_start_position" : "A4"
  "result_start_position" : "B4"

"SUITI_66":
  "title" : "安吉县各乡镇（街道）限制因素评级表"
  "values" : "MJ"
  "field" : "DLBM"
  "new_field" : "DLDLMC"
  "new_field_name" : ["耕地", "园地", "林地", "草地", "其他"]
  "new_field_name_rule" : ["'^01'", "'^02'", "'^03'", "'^04'", "'^(?!(01|02|03|04))'"]
  "index" : ['DLDLMC', 'ZZSXMC']
  "columns" : ['s_name']
  "columns_values" : ["适宜耕地", "适宜园地", "适宜林地", "适宜草地", "All"]
  "col_name_list": [[0, "耕地"],[0, "园地"],[1, "园地", "工程恢复"],[1, "园地", "即可恢复"],[0, "林地"],[1, "林地", "工程恢复"],[1, "林地", "即可恢复"],[0, "草地"],[1, "草地", "工程恢复"],[1, "草地", "即可恢复"],[0, "其他"], [0, "All"]]
  "result_start_position" : "D3"
  "percent_start_position" : "D4"

"JSBG_106":
  "title" : "安吉县土壤表层样品数据预处理"
  "values" : ['count', 'min', 'max', 'mean', 'std']
  "fields" : ['PH', 'CEC', 'OM', 'TN', 'TP', 'TK', 'AP', 'AK', 'TRRZPJZ', 'GZCHD', 'JXZC1', 'JXZC2']
  "rule" : "x != -9999"
  "col_start_position" : "A3"
  "value_start_position" : "B2"
  "result_start_position" : 'B3'

"JSBG_108":
  "title" : "安吉县土类理化性状特征统计表"
  "field" : 'TL'
  "weight" : "MJ"
  "values" : ['PH', 'CEC', 'TRRZPJZ', 'GZCHD', 'TRNL', 'TRSL', 'TRFSL']
  "col_start_position" : "A3"
  "value_start_position" : "C2"
  "result_start_position" : 'C3'

"JSBG_109":
  "title" : "安吉县土类肥力特征统计表"
  "field" : 'TL'
  "weight" : "MJ"
  "values" : ['OM', 'TN', 'TP', 'TK', 'AP', 'AK']
  "col_start_position" : "A3"
  "value_start_position" : "C2"
  "result_start_position" : 'C3'

"JSBG_001":
  "title" : "安吉县土地利用类型下土壤类型面积统计表"
  "values" : "MJ"
  "field" : "DLBM"
  "new_field" : "DLDLMC"
  "new_field_name" : ["耕地", "园地", "林地", "草地", "其他"]
  "new_field_name_rule" : ["'^01'", "'^02'", "'^03'", "'^04'", "'^(?!(01|02|03|04))'"]
  "index" : ['TL', 'YL', 'TS', 'TZ']
  "columns" : ['DLDLMC']
  "col_start_position" : "A4"
  "row_start_position" : "E3"
  "result_start_position" : "E4"

# type 13 开始
"sample_joined" : ['DLBM','DLMC','TL', 'YL', 'TS', 'TZ', 'TRZD']

"JSBG_013":
  "title" : "安吉县表层样点土壤质地统计表"
  "values" : "MJ"
  "index" : ['DLDLMC']
  "columns" : ['TRZD']
  "col_start_position" : "A3"
  "row_start_position" : "C2"
  "result_start_position" : "C3"
  "percent_start_position" : "C4"

"JSBG_015":
  "title" : "安吉县表层样点土壤质地统计表"
  "values" : "MJ"
  "index" : ['XZQMC']
  "columns" : ['TRZD']
  "col_start_position" : "A3"
  "row_start_position" : "C2"
  "result_start_position" : "C3"
  "percent_start_position" : "C4"
# type 13 结束


"JSBG_014":
  "title" : "安吉县表层样点土壤质地统计表"
  "values" : ['JXZC1','JXZC2','JXZC3','JXZC4']
  "index" : ['DLDLMC']
  "columns" : []
  "col_start_position" : "A4"
  "row_start_position" : "B3"
  "result_start_position" : "B4"
