"QUAL_72":
  "title" : "安吉县耕地质量等级面积及其占比"
  "group_field" : dj
  "group_field_values" : [1,2,3,4,5,6,7,8,9,10]
  "calc_field" : 'MJ'
  "start_position" : "B3"
  "seg_length" : 5
  "position_interval" : 3

"SUITI_62":
  "title" : "安吉县适宜类评价面积表"
  "group_field" : s_level
  "group_field_values" : [1,2,3,4,5,6]
  "calc_field" : 'MJ'
  "start_position" : "B3"
  "seg_length" : 0
  "position_interval" : 0

"QUAL_73":
  "title" : "安吉县各乡镇（街道）耕地评价综合指数及质量等级表"
  "limit_field" : "XZQMC"
  "calc_field" : 'MJ'
  "weight_field": "score"
  "street_start_position" : "A3"
  "score_start_position" : "B3"
  "level_start_position" : "C3"
  "level_table":
    - "level_name": "一等"
      "range": (x >= 0.9070)
    - "level_name": "二等"
      "range": (x >= 0.8806 and x < 0.9070)
    - "level_name": "三等"
      "range": (x >= 0.8543 and x < 0.8806)
    - "level_name": "四等"
      "range": (x >= 0.8279 and x < 0.8543)
    - "level_name": "五等"
      "range": (x >= 0.8015 and x < 0.8279)
    - "level_name": "六等"
      "range": (x >= 0.7751 and x < 0.8015)
    - "level_name": "七等"
      "range": (x >= 0.7488 and x < 0.7751)
    - "level_name": "八等"
      "range": (x >= 0.7224 and x < 0.7488)
    - "level_name": "九等"
      "range": (x >= 0.6960 and x < 0.7224)
    - "level_name": "十等"
      "range": (x < 0.6960)

"QUAL_74":
  "title" : "安吉县各乡镇（街道）耕地质量等级面积分布表"
  "limit_field" : "XZQMC"
  "calc_field" : 'MJ'
  "group_field" : 'dj'
  "group_field_value" : [1,2,3,4,5,6,7,8,9,10]
  "street_start_position": "A4"
  "result_start_position": "C4"

"SUITI_56":
  "title" : "安吉县各乡镇（街道）土壤坡度等级面积分布表"
  "limit_field" : "XZQMC"
  "calc_field" : 'MJ'
  "group_field" : 'PD_new'
  "group_field_value" : [0,1,2,3,4,5]
  "street_start_position": "A4"
  "result_start_position": "C4"

"SUITI_57":
  "title" : "安吉县各乡镇（街道）土壤土层厚度等级面积分布表"
  "limit_field" : "XZQMC"
  "calc_field" : 'MJ'
  "group_field" : 'TCHD_new'
  "group_field_value" : [0,1,2,3,4,5]
  "street_start_position": "A4"
  "result_start_position": "C4"

"SUITI_58":
  "title" : "安吉县各乡镇（街道）土壤地表砾石丰度等级面积分布表"
  "limit_field" : "XZQMC"
  "calc_field" : 'MJ'
  "group_field" : 'DBLSFD_new'
  "group_field_value" : [0,1,2,3,4,5]
  "street_start_position": "A4"
  "result_start_position": "C4"

"SUITI_59":
  "title" : "安吉县各乡镇（街道）土壤质地等级等级面积分布表"
  "limit_field" : "XZQMC"
  "calc_field" : 'MJ'
  "group_field" : 'TRZD_new'
  "group_field_value" : [0,1,2,3,4,5]
  "street_start_position": "A4"
  "result_start_position": "C4"

"SUITI_60":
  "title" : "安吉县各乡镇（街道）土壤水资源条件等级面积分布表"
  "limit_field" : "XZQMC"
  "calc_field" : 'MJ'
  "group_field" : 'SZYTJ_new'
  "group_field_value" : [0,1,2,3,4,5]
  "street_start_position": "A4"
  "result_start_position": "C4"

"SUITI_61":
  "title" : "安吉县各乡镇（街道）土壤排水能力等级面积分布表"
  "limit_field" : "XZQMC"
  "calc_field" : 'MJ'
  "group_field" : 'PSNL_new'
  "group_field_value" : [0,1,2,3,4,5]
  "street_start_position": "A4"
  "result_start_position": "C4"

"SUITI_164":
  "title" : "安吉县各乡镇（街道）土壤侵蚀程度等级面积分布表"
  "limit_field" : "XZQMC"
  "calc_field" : 'MJ'
  "group_field" : 'QSCD_new'
  "group_field_value" : [0,1,2,3,4,5]
  "street_start_position": "A4"
  "result_start_position": "C4"

"SUITI_165":
  "title" : "安吉县各乡镇（街道）土壤盐碱化等级面积分布表"
  "limit_field" : "XZQMC"
  "calc_field" : 'MJ'
  "group_field" : 'TRYJH_new'
  "group_field_value" : [0,1,2,3,4,5]
  "street_start_position": "A4"
  "result_start_position": "C4"

"SUITI_166":
  "title" : "安吉县各乡镇（街道）土壤基岩出露丰度等级面积分布表"
  "limit_field" : "XZQMC"
  "calc_field" : 'MJ'
  "group_field" : 'JYCLFD_new'
  "group_field_value" : [0,1,2,3,4,5]
  "street_start_position": "A4"
  "result_start_position": "C4"

"QUAL_75":
  "title" : "安吉县各乡镇（街道）耕地粮食生产潜能表"
  "limit_field" : "XZQMC"
  "calc_field" : 'MJ'
  "weight_field" : 'CN'
  "dl_field" : 'DLBM'
  "dl_rule": "'^01.*'"
  "street_start_position": "A4"
  "result_start_position": "B4"

"SUITI_63":
  "title" : "安吉县土壤类型（亚类）适宜类评价分布表"
  "limit_field" : "YL"
  "calc_field" : 'MJ'
  "group_field" : 's_level'
  "group_field_value" : [1,2,3,4,5,6]
  "col_start_position": "A4"
  "result_start_position": "C4"

"SUITI_64":
  "title" : "安吉县土壤农业利用适宜程度评价面积表"
  "limit_field" : "s_s_level"
  "calc_field" : 'MJ'
  "group_field" : 's_name'
  "group_field_value" : ['适宜耕地','适宜园地','适宜林地','适宜草地']
  "col_start_position": "A4"
  "result_start_position": "C4"