"add_field":
  "origin_fields":
    - "name": "DLBM"
      "include": "01"
    - "name": "DLBM"
      "include": "02"
    - "name": "DLBM"
      "include": "03"
    - "name": "DLBM"
      "include": "04"
  "new_fields":
    -
      - "name": "HBDLBM"
        "value": "01"
      - "name": "HBDLMC"
        "value": "耕地"
    -
      - "name": "HBDLBM"
        "value": "02"
      - "name": "HBDLMC"
        "value": "园地"
    -
      - "name": "HBDLBM"
        "value": "03"
      - "name": "HBDLMC"
        "value": "林地"
    -
      - "name": "HBDLBM"
        "value": "04"
      - "name": "HBDLMC"
        "value": "草地"